### PR TITLE
Unittests for ws.py + custom connection_env

### PR DESCRIPTION
**Pull request by DominiqueFuchs**
This PR would introduce:

1. The ability to use a custom endpoint URL for a KrakyWsClient instance via connection_env. As it is, connection_env already has a default value of 'production' on instance initialization, so that the final else clause in _connect_ would normally never be reached - so I utilized it to provide a way to use the provided string as a custom URL if none of the predefined names match
2. Some basis unittests for ws.py that cover _connect_, _disconnect_, as well as subscriptions and the underlying __send_ utilization. Here, a custom connection_env is used to point at the dummy ws server from conftest.py

### CODE REVIEW

**Comment by Atem18** [comment]
@DominiqueFuchs Thanks a lot for the PR. It is nearly working, can you rebase from main, as I added pytest-asyncio as test dependency so that async tests can pass ?

**Comment by DominiqueFuchs** [comment]
Seems to run fine now - only thing left in logs are warnings due to the destroyed task, but these simply stem from the fact that I'm not cleaning up (always shutting down w/ disconnect and awaiting) in the unittests that do not explicitly test the disconnect functionality to keep them small and isolated - they do not affect the test results. If desired, one could simply add the needed cleanup in al unit tests to prevent those warnings.

**Comment by Atem18** [comment]
Can you add the cleanup so the tests runs without any warnings ? Thanks a lot in advance.

**Comment by DominiqueFuchs** [comment]
Done, all websocket unittests now await disconnect on exit, no destroyed tasks in the test log anymore

**Comment by Atem18** [comment]
@DominiqueFuchs Thanks a lot, I will merge it !

**Pull request merged**
